Repository pharmaverse/admiralvaccine, pull requests merged in 2023-03, with the labels that each got.

#59 Closes #54
  data/is.rda
  inst/templates/ad_adis.R
Labels: enhancement, help wanted

#46 41_adface maxsev utility@devel
  NAMESPACE
  R/admiralvaccine.R
  R/derive_param_maxsev_draft.R
  R/global.R
  man/derive_param_maxsev.Rd
  tests/testthat/test-test-derive_param_maxsev.R
Labels: documentation, enhancement

#67 Closes #66
  R/derive_param_maxsev_draft.R
  data/is.rda
  inst/WORDLIST
  inst/templates/ad_adis.R
Labels: help wanted

#69 Close #65
  NAMESPACE
  R/admiralvaccine.R
  R/derive_vars_crit.R
  admiralvaccine.Rproj
  inst/WORDLIST
  man/derive_vars_crit.Rd
  tests/testthat/test-test-derive_vars_crit.R
Labels: help wanted
