Repository pharmaverse/admiralvaccine, pull requests merged in 2023-02, with the labels that each got.

#33 Closes #26
  .Rbuildignore
  .gitignore
  .lycheeignore
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/IS_SUPPIS.R
  R/admiralvaccine.R
  R/data.R
  R/my_first_fcn.R
  README.md
  _pkgdown.yml
  data/is.rda
  data/suppis.rda
  inst/WORDLIST
  inst/templates/ad_adis.R
  inst/templates/ad_adxx.R
  man/admiralvaccine-package.Rd
  man/is.Rd
  man/suppis.Rd
  renv.lock
  renv/.gitignore
  renv/activate.R
Labels: documentation, enhancement

#37 5 readme update@devel
  README.Rmd
  README.md
  inst/WORDLIST
Labels: documentation

#52 Closes #30 Creating ADIS Workflow: Step 3
  inst/templates/ad_adis.R
Labels: help wanted
