Repository pharmaverse/admiralvaccine, pull requests merged in 2023-06, with the labels that each got.

#186 185 resolve lintr and roxygen issues
  R/derive_var_aval_adis.R
  R/derive_vars_params.R
  inst/templates/ad_adis.R
  tests/testthat/test-derive_vars_params.R
  vignettes/adce.Rmd
  vignettes/adis.Rmd
Labels: bug, final review

#180 176 update derive param fever occur function
  NAMESPACE
  R/derive_fever_records.R
  R/global.R
  inst/templates/ad_adface.R
  man/derive_diam_to_sev_records.Rd
  man/derive_fever_records.Rd
  man/derive_param_maxdiam.Rd
  man/derive_param_maxsev.Rd
  man/derive_param_maxtemp.Rd
  tests/testthat/test-derive_fever_records.R
  vignettes/adface.Rmd
Labels: enhancement, final review

#171 164 updates on derive vars max flag function
  NAMESPACE
  R/derive_vars_max_flag.R
  inst/WORDLIST
  man/derive_var_aval_adis.Rd
  man/derive_vars_crit.Rd
  man/derive_vars_event_flag.Rd
  man/derive_vars_max_flag.Rd
  man/derive_vars_merged_vaccine.Rd
  man/derive_vars_params.Rd
  man/derive_vars_vaxdt.Rd
  man/max_flag.Rd
  tests/testthat/test-derive_vars_max_flag.R
Labels: enhancement, final review

#172 165 update derive vars merged vaccine@devel
  R/derive_vars_merged_vaccine.R
  man/derive_vars_merged_vaccine.Rd
Labels: final review

#175 163 derive vars event flag@devel
  R/derive_vars_event_flag.R
  man/derive_vars_event_flag.Rd
  tests/testthat/test-derive_vars_event_flag.R
Labels: final review

#170 159 update derive vars params@devel
  R/derive_vars_params.R
  man/derive_vars_params.Rd
Labels: final review

#177 Closes #162
  .Rprofile
  .github/workflows/common.yml
  R/derive_var_aval_adis.R
  R/derive_vars_crit.R
  inst/WORDLIST
  inst/templates/ad_adce.R
  inst/templates/ad_adis.R
  man/derive_var_aval_adis.Rd
  man/derive_vars_crit.Rd
  renv.lock
  renv/.gitignore
  renv/activate.R
  renv/settings.dcf
  tests/testthat/test-derive_vars_crit.R
  vignettes/adce.Rmd
  vignettes/adis.Rmd
  vignettes/adsl.Rmd
Labels: enhancement, final review

#191 189 update adface template vignette@devel
  NAMESPACE
  R/admiralvaccine.R
  R/derive_diam_to_sev_records.R
  R/derive_param_maxdiam.R
  R/derive_param_maxsev.R
  R/derive_param_maxtemp.R
  R/derive_vars_vaxdt.R
  inst/WORDLIST
  inst/templates/ad_adface.R
  man/derive_diam_to_sev_records.Rd
  man/derive_fever_records.Rd
  man/derive_param_maxdiam.Rd
  man/derive_param_maxsev.Rd
  man/derive_param_maxtemp.Rd
  tests/testthat/test-derive_param_maxdiam.R
  tests/testthat/test-derive_param_maxsev.R
  tests/testthat/test-derive_param_maxtemp.R
  vignettes/adce.Rmd
  vignettes/adface.Rmd
  vignettes/adis.Rmd
Labels: documentation, enhancement

#204 203 update website@devel
  R/data.R
  R/derive_diam_to_sev_records.R
  R/derive_vars_crit.R
  R/derive_vars_event_flag.R
  R/derive_vars_max_flag.R
  R/derive_vars_merged_vaccine.R
  README.Rmd
  man/derive_diam_to_sev_records.Rd
  man/derive_vars_crit.Rd
  man/derive_vars_event_flag.Rd
  man/derive_vars_max_flag.Rd
  man/derive_vars_merged_vaccine.Rd
  man/vx_adsl.Rd
  man/vx_ce.Rd
  man/vx_dm.Rd
  man/vx_ex.Rd
  man/vx_face.Rd
  man/vx_is.Rd
  man/vx_suppce.Rd
  man/vx_suppdm.Rd
  man/vx_suppex.Rd
  man/vx_suppface.Rd
  man/vx_suppis.Rd
  man/vx_vs.Rd
  vignettes/adface.Rmd
  vignettes/admiralvaccine.Rmd
  vignettes/adsl.Rmd
Labels: bug, documentation, final review
